repos:
  - repo: https://github.com/eslint/eslint
    rev: v8.13.0
    hooks:
      - additional_dependencies:
          - "@typescript-eslint/eslint-plugin@5.18.0" # String due to @ prefix
          - "@typescript-eslint/parser@5.18.0"
          - eslint@8.13.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-react@7.29.4
          - eslint-plugin-react-hooks@4.4.0
        id: eslint
        types:
          - file
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
        exclude: package-lock.json
      - id: trailing-whitespace
        exclude_types:
          - markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude_types:
          - json
